name: social_cv_client_flutter
description: A new CV application.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.3

  # Web Client
  http: ^0.13.4
  dio: ^4.0.4

  # Routes
  fluro: ^2.0.3

  # Async/Rx
  async: ^2.8.1
  rxdart: ^0.27.3

  # Bloc Pattern
  flutter_bloc: ^8.0.0
  bloc: ^8.0.1

  # Dependency Injection
  provider: ^6.0.1

  # Storage
  shared_preferences: ^2.0.9

  # Serialization
  json_annotation: ^4.3.0

  # Translations
  intl: ^0.17.0

  # UI Widgets
  transparent_image: ^2.0.0

  uuid: 3.0.5

  # Icons
  material_design_icons_flutter: ^5.0.6295
  #cupertino_icons: ^0.1.0

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/account_card_details-white.png
    - assets/images/account_card_details-blue.png
    - assets/images/default-avatar.png
    - assets/images/default-banner.jpg
    - assets/images/login_logo.png
    - config.json # secret data


  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
